#!/usr/bin/env bash

set -e -u

# Get env variable name
path_env=$(echo $1 | upper)

# Translates /home/$USER to ~/
shorten-home() {
	sed "s#$HOME#~#g"
}

# Split by delimitor : for the env variable matching the variable name
# e.g. manpath becomes $MANPATH
IFS=':' read -ra SYSPATH <<<"${!path_env}"

# Print LABEL
echo -e "\n[${path_env}]"
for path in "${SYSPATH[@]}"; do
	echo $path | shorten-home
done
